### ISSUE TITLE
Kernel boot time ahead of CSV

### ISSUE THREAD

**Issue by ro0NL** [sourceability/console-toolbar-bundle#14]
I was trying this bundle, without success.

Upon debugging i figured the profiles are filtered out based on kernel boot time (which theoretically makes sense :))

First run:

```
^ "Profile: 2022-07-12 12:25:36"
^ "Kernel:  2022-07-12 12:26:21"
```

Second run:

```
^ "Profile: 2022-07-12 12:26:22"
^ "Kernel:  2022-07-12 12:26:28"
^ "Profile: 2022-07-12 12:25:36"
^ "Kernel:  2022-07-12 12:26:28"
```

Im not entirely sure why profiles are stored first :thinking: nor do i have another solution, but perhaps food for thought.

**Comment by adrienbrault** [comment]
Hey, nothing comes to mind with that context, but let's try to figure this out :).

Could you provide more information about how you've configured the differents bundles, your environment php/symfony versions and how you're using the bundle (behat, phpunit, etc).

**Comment by ro0NL** [comment]
im using the`bin/console ... --toolbar` integration

sf 4.4 / php 7.4 / containerized

i will try to debug the order of execution soonish :+1:

**Comment by ro0NL** [comment]
@adrienbrault reading comes before writing somehow ... thus a priority issue.

```
^ "Sourceability\ConsoleToolbarBundle\EventListener\ConsoleToolbarListener::onTerminate" // reads
^ "Sourceability\Instrumentation\EventListener\CommandProfilerListener::onTerminate" // writes
```
